pull_request_rules:
  - name: Automatic merge ⬇️ on approval ✔
    conditions:
      - "approved-reviews-by=[niklasstoffers]"
      - check-success=build
      - check-success=test
      - base=main
    actions:
      merge:
        method: merge