version: '3.8'
services:
  hainz-db:
    container_name: hainz-db
    image: postgres:15.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USERNAME}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DATABASE}
    ports:
      - '5432:${POSTGRES_PORT}'
    volumes:
      - db:/var/lib/postgresql/data
  hainz-redis:
    container_name: hainz-redis
    image: redis:7.0.7-alpine
    restart: always
    command: redis-server --save ${REDIS_SAVE_AFTER_SECONDS} ${REDIS_SAVE_AFTER_WRITES} --loglevel warning
    ports:
      - '6379:${REDIS_PORT}'
    volumes:
      - cache:/data
  hainz-app:
    container_name: hainz-app
    image: hainz-app
    restart: always
    build: .
    depends_on:
      - hainz-db
      - hainz-redis
    environment:
      - PERSISTENCE_USERNAME=${POSTGRES_USERNAME}
      - PERSISTENCE_PASSWORD=${POSTGRES_PASSWORD}
      - PERSISTENCE_HOSTNAME=hainz-db
      - PERSISTENCE_PORT=${POSTGRES_PORT}
      - PERSISTENCE_DB=${POSTGRES_DATABASE}
      - CACHE_HOSTNAME=hainz-redis
      - CACHE_PORT=${REDIS_PORT}

volumes:
  db:
    driver: local
  cache:
    driver: local