name: Auto approve

on: pull_request_target

jobs:
  auto-approve:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    if: github.actor == 'niklasstoffers' && contains(github.event.comment.body, 'LGTM')
    steps:
      - uses: hmarr/auto-approve-action@v3
        with:
          review-message: "LGTM too"
