name: TEST

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore tests/Hainz.Tests
    - name: Build
      run: dotnet build tests/Hainz.Tests --no-restore
    - name: Test
      run: dotnet test tests/Hainz.Tests --no-build --verbosity normal
